### PR TITLE
WIP: Added scripts to tar and ingest data into IRODS

### PR DESCRIPTION
**Pull request by julianpistorius**
Work related to https://github.com/AgPipeline/computing-pipeline/issues/38

Not sure it should be merged at all, or if it is, which repo is best for it to go to.

### CODE REVIEW

**Review by Chris-Schnaufer — APPROVED** [review]

**Comment by Chris-Schnaufer** [comment]
@julianpistorius Are you going to merge this?

**Comment by julianpistorius** [comment]
> @julianpistorius Are you going to merge this?

Hi @Chris-Schnaufer. No. See my comment:

> Not sure it should be merged at all, or if it is, which repo is best for it to go to.

This is something to be handed over to Eric & his team.

**Comment by Chris-Schnaufer** [comment]
@julianpistorius Can you move it to https://github.com/uacic?

**Comment by Chris-Schnaufer** [comment]
Closing PR since the code needs to be merged elsewhere

**Pull request closed without merging**
